USE `eureka-project-db`;

-- Insertar datos mock en Departments
INSERT INTO departments (name) VALUES
('Ventas'),
('Recursos Humanos'),
('Contabilidad');

-- Insertar datos mock en Users
INSERT INTO users (name, email, department_id) VALUES
-- Departamento 1 (17 usuarios)
('Juan Pérez', 'juan.perez@example.com', 1),
('María González', 'maria.gonzalez@example.com', 1),
('Carlos Fernández', 'carlos.fernandez@example.com', 1),
('Laura Torres', 'laura.torres@example.com', 1),
('Miguel Díaz', 'miguel.diaz@example.com', 1),
('Sofía Morales', 'sofia.morales@example.com', 1),
('Andrés Romero', 'andres.romero@example.com', 1),
('Paula Jiménez', 'paula.jimenez@example.com', 1),
('Diego Castillo', 'diego.castillo@example.com', 1),
('Valentina Rojas', 'valentina.rojas@example.com', 1),
('Ricardo Silva', 'ricardo.silva@example.com', 1),
('Camila Herrera', 'camila.herrera@example.com', 1),
('Jorge Vega', 'jorge.vega@example.com', 1),
('Isabella Navarro', 'isabella.navarro@example.com', 1),
('Fernando Cruz', 'fernando.cruz@example.com', 1),
('Natalia Soto', 'natalia.soto@example.com', 1),
('Alejandro Paredes', 'alejandro.paredes@example.com', 1),

-- Departamento 2 (25 usuarios)
('Pedro Sánchez', 'pedro.sanchez@example.com', 2),
('Ana Martínez', 'ana.martinez@example.com', 2),
('Lucía Ramírez', 'lucia.ramirez@example.com', 2),
('Javier Ortiz', 'javier.ortiz@example.com', 2),
('Carla Mendoza', 'carla.mendoza@example.com', 2),
('Manuel Flores', 'manuel.flores@example.com', 2),
('Gabriela Castro', 'gabriela.castro@example.com', 2),
('Ricardo Peña', 'ricardo.pena@example.com', 2),
('Valeria Aguirre', 'valeria.aguirre@example.com', 2),
('Héctor Rivas', 'hector.rivas@example.com', 2),
('Lorena Salazar', 'lorena.salazar@example.com', 2),
('Santiago Bravo', 'santiago.bravo@example.com', 2),
('Daniela Pino', 'daniela.pino@example.com', 2),
('Andrés Molina', 'andres.molina@example.com', 2),
('Renata Figueroa', 'renata.figueroa@example.com', 2),
('Patricio Fuentes', 'patricio.fuentes@example.com', 2),
('Camila Soto', 'camila.soto@example.com', 2),
('Sebastián Cárdenas', 'sebastian.cardenas@example.com', 2),
('Florencia Vidal', 'florencia.vidal@example.com', 2),
('Martín Rojas', 'martin.rojas@example.com', 2),
('Natalia León', 'natalia.leon@example.com', 2),
('Felipe Herrera', 'felipe.herrera@example.com', 2),
('Isabel Paredes', 'isabel.paredes@example.com', 2),
('Gonzalo Bravo', 'gonzalo.bravo@example.com', 2),
('Antonella Vega', 'antonella.vega@example.com', 2),

-- Departamento 3 (20 usuarios)
('Luis Rodríguez', 'luis.rodriguez@example.com', 3),
('Sofía López', 'sofia.lopez@example.com', 3),
('Diego Torres', 'diego.torres@example.com', 3),
('Martín Castillo', 'martin.castillo@example.com', 3),
('Camila Aguirre', 'camila.aguirre@example.com', 3),
('Rodrigo Peña', 'rodrigo.pena@example.com', 3),
('Isabella Rojas', 'isabella.rojas@example.com', 3),
('Francisco Vega', 'francisco.vega@example.com', 3),
('Luciana Molina', 'luciana.molina@example.com', 3),
('Alejandro Pino', 'alejandro.pino@example.com', 3),
('Daniela Bravo', 'daniela.bravo@example.com', 3),
('Fernando Salazar', 'fernando.salazar@example.com', 3),
('Valentina León', 'valentina.leon@example.com', 3),
('Patricio Castro', 'patricio.castro@example.com', 3),
('Renata Rivas', 'renata.rivas@example.com', 3),
('Jorge Fuentes', 'jorge.fuentes@example.com', 3),
('Laura Figueroa', 'laura.figueroa@example.com', 3),
('Andrés Navarro', 'andres.navarro@example.com', 3),
('Gabriela Paredes', 'gabriela.paredes@example.com', 3),
('Camilo Herrera', 'camilo.herrera@example.com', 3);
